### ISSUE TITLE
`berkeley`: Update minter to use first typecode when pattern contains multiple typecodes

### ISSUE THREAD

**Issue by kheal** [microbiomedata/nmdc-runtime#592]
In berkeley-schema-fy24, some of the syntax declarations on ids of classes result in extra parentheses during minting on the berkeley-schema nmdc runtime. This results in badly minted ids for instances of new classes.

There are two existing classes in the berkeley schema where the id typecodes need to be either "dgns" or "omprc", but the minter should only mint IDs for "dgns".

This class
```
NucleotideSequencing:
    class_uri: nmdc:NucleotideSequencing
    is_a: DataGeneration
    slot_usage:
      id:
        structured_pattern:
          syntax: "{id_nmdc_prefix}:(dgns|omprc)-{id_shoulder}-{id_blade}$"
          interpolated: true
```
Needs to mint ids with dgns (not omprc).  

**Criteria for Completion**

minting for `NucleotideSequencing` and `MassSpectrometry` classes generates ids with typecodes "dgns" and "dgms" respectively.  

Reference: https://github.com/microbiomedata/nmdc-schema/issues/2122
