### ISSUE TITLE
GHA: Separate container `build` and `run` steps to simplify reading workflow logs

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#640]
The `python-app.yml` workflow currently invokes:
```yaml
    - name: Test with pytest
      run: |
        make up-test
        make test
```

That step takes a long time (several minutes) and produces a lot of console output (many scrolls). I find it tedious to scroll through the console output in order to find the portion that shows the test output.

I propose the GHA workflow be updated so that the container building step happen in a different workflow step from the actual running of the tests.
