### ISSUE TITLE
Add Forwarded-Allow-IPs to runtime config in rancher

### ISSUE THREAD

**Issue by shreddd** [microbiomedata/nmdc-runtime#882]
Based on:
https://github.com/fastapi/fastapi/discussions/9328
https://stackoverflow.com/questions/63511413/fastapi-redirection-for-trailing-slash-returns-non-ssl-link
FASTAPI returns internal redirects to http instead of https

This is not a major issue, since Cloudflare and HSTS will make sure all incoming traffic is always over HTTPS but it is still something that should be fixed 
To ensure proper redirect https URLs we need to add annotations to the ingress and pass in the correct flag to uvicorn

Kubernetes Ingress:
```yaml
nginx.ingress.kubernetes.io/enable-real-ip: 'true'
nginx.ingress.kubernetes.io/proxy-real-ip-cidr: 10.42.0.0/16
nginx.ingress.kubernetes.io/use-forwarded-headers: 'true'`
```

And the uvicorn startup flag:

```
uvicorn nmdc_runtime.api.main:app --proxy-headers --host 0.0.0.0 --port 8000 --forwarded-allow-ips '10.42.0.0/16'
```
where 10.42.0.0/16 is the internal network for Spin

Tasks:
- [ ] Enable ingress annotations - dev
- [ ] Enable uvicorn startup flag - dev
- [ ] Enable ingress annotations - sandbox
- [ ] Enable uvicorn startup flag - sandbox
- [ ] Enable ingress annotations - prod
- [ ] Enable uvicorn startup flag - prod
